---
- name: Provision AMI image with IDA STATUS
  remote_user: ec2-user
  hosts: default
  vars:
    target_major_version: "{{ ansible_facts['distribution_major_version'] }}"
    target_family: "{{ ansible_facts['os_family']|lower }}"
    target: "{{ target_family }}{{ target_major_version }}"

    # common variables
    python_version: "3.9.7"
    python_minor_version: "3.9"
    python_package_name: "python39"
    pip_executable_target: /bin/pip3.9
    src_dir: "/usr/local/src"
    ida_dir: "/usr/local/ida"
    tmp_dir: "/tmp"
    geotool_src_dir: "/usr/local/src/geotool"
    ida_scripts_dir: "/usr/local/scripts"
    python_modules_dir: "/ida/local/modules-py"
    local_bin_dir: "/usr/local/bin/"
    local_man_dir: "/usr/local/share/man/"
    work_dir: "/tmp/stationxml-workdir/"

  tasks:
    - debug:
        msg: "home_location: {{ home_location }}"

    - debug:
        msg: "git_branch: {{ git_branch }}"

    - import_role:
        name: idastatus-base
      vars:
        idastatus_src_version: ""  # currently unused, but should in future, pull from github "release" version
        system_hostname: idastatus
        home_root: "{{ home_location }}"
        idadcc_home_dir : "{{ home_location }}/idadcc" # NOTE need to verify this
        git_src_branch: "{{ git_branch }}"

