# os_family == 'redhat' SYSTEM SPECIFIC
- name: Enable EPEL repo on AWS EC2 Amazon Linux 2 Instances
  shell: |
    amazon-linux-extras install epel -y
  when: is_ec2
  become: true

- name: install pkgs
  yum:
    state: latest
    update_cache: yes
    name: 
        - docker
        - libmng
        - xorg-x11-server-Xorg
        - "@Development Tools"
        - gcc
        - make
        - wget
        - ftp
        - libkadm5
        - libcom_err-devel
        - libsepol-devel
        - zlib-devel
        - pcre-devel
        - libselinux-devel
        - libverto-devel
        - keyutils-libs-devel
        - krb5-devel
        - openssl-devel
        - bzip2-devel
        - libffi-devel
        - libcurl-devel
        - tcl
        - tk
        - golang
        - tree
        - telnet
        - tmux
        - git
        - libsqlite3x
        - gitflow
        - jq
        - certbot
        - python2-certbot-nginx.noarch
        - nginx
  tags:
    - packages
  become: true

